services:

  wwebjs-api:
    image: avoylenko/wwebjs-api:v1.34.6
    container_name: ws-wwebjs
    restart: unless-stopped
    environment:
      - API_KEY=${WWEBJS_API_KEY}
      - BASE_WEBHOOK_URL=https://n8n.simplificia.com.ar
      - ENABLE_WEBHOOK=false
    volumes:
      - ./sessions:/usr/src/app/sessions
    shm_size: '512mb'
    networks:
      - n8n_default
    labels:
      - "traefik.enable=false"

networks:
  n8n_default:
    external: true
